### ISSUE TITLE
A question about transformation

### ISSUE THREAD

**Issue by monchin** [Theorell/DepecheR#6]
Hello, I knew DEPECHE from a paper <i>[A comparison framework and guideline of clustering methods for mass cytometry data](https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-019-1917-7)</i>, and have just read your paper. 
I think this method is excellent, but for transformation, I knew flow and mass cytometry data are with narrow range in low expression and wide range in high expression, so almost all other methods use `logicle` or `asinh`  or so to transform data at first. But in your paper, it said DEPECHE only does log transformation when the kurtosis of data is high. So, my question is, why can DEPECHE be different from other methods in transformation? What if we do logicle or asinh transformation before DEPECHE?
Thank you!

**Comment by jtheorell** [comment]
Dear @monchin, 
Thank you very much for this question! We are no different from all the other methods in this regard: when it comes to flow or mass cytometry data, the in-data is expected to be pre-transformed. This is clear from the [DepecheR package vinjette](https://bioconductor.org/packages/release/bioc/vignettes/DepecheR/inst/doc/DepecheR_test.html). In the paper, I am sorry to say that this does not seem to be clearly stated in the main results or methods sections, but is rather implicit. It is however stated in the final section of the experimental procedures section that the mass cytometry data was pre-transformed before use in any of the methods. I hope this answers your question. If not or if other issues arise, please do not hesitate to contact us again! I hope you will find the method, and the BioConductor package, useful. 
Best regards
Jakob Theorell

**Comment by monchin** [comment]
> Dear @monchin,
> Thank you very much for this question! We are no different from all the other methods in this regard: when it comes to flow or mass cytometry data, the in-data is expected to be pre-transformed. This is clear from the [DepecheR package vinjette](https://bioconductor.org/packages/release/bioc/vignettes/DepecheR/inst/doc/DepecheR_test.html). In the paper, I am sorry to say that this does not seem to be clearly stated in the main results or methods sections, but is rather implicit. It is however stated in the final section of the experimental procedures section that the mass cytometry data was pre-transformed before use in any of the methods. I hope this answers your question. If not or if other issues arise, please do not hesitate to contact us again! I hope you will find the method, and the BioConductor package, useful.
> Best regards
> Jakob Theorell

Thank you very much for your kind reply! I got it!
